# Generated by Django 2.0.5 on 2018-05-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='creator',
            field=models.CharField(default='Hristiyan Bonev', max_length=150),
            preserve_default=False,
        ),
    ]
